### ISSUE TITLE
How Can I trace the previous state?

### ISSUE THREAD

**Issue by chenkan1994** [digint/tinyfsm#1]
Hello, Is there any elegant solution to trace the previous state?
Sometimes this demand is reasonable.

**Comment by digint** [comment]
It's been quite a while since I last used tinyfsm, but enabling the DBG statements (e.g. [here](/digint/tinyfsm/blob/master/include/tinyfsm.hpp#L133) used to help a lot for tracing what is going on.

Or perhaps you might want to store some last_state before changing current_state [somewhere here](/digint/tinyfsm/blob/master/include/tinyfsm.hpp#L135).

PS sorry for the late reply, the mails for this (old) repo went to the wrong folder...

**Comment by chenkan1994** [comment]
I saved last_state outside class Fsm and it works, thanks anyway!
