### ISSUE TITLE
any plan for latest tag release ? 

### ISSUE THREAD

**Issue by sequoiar** [digint/tinyfsm#29]
Is there any plan for a tag release ?

**Comment by digint** [comment]
Do you mean a relase 0.3.3 based on latest master?

I thought I can wait a bit, as there is no functional changes since 0.3.2

  * Remove size -B option in makefiles.
  * Add library.json for PlatformIO.
  * Tidy elevator example.

https://github.com/digint/tinyfsm/compare/v0.3.2...master

But yeah, latest release is from 2018, so maybe I waited "long enough" to get those minor changes into a new release.

**Comment by sequoiar** [comment]
@digint if so, can we do a 1.0.0 tag release ?

**Comment by dzarda** [comment]
PIO metafile is a significant reason in itself to justify a release IMHO

**Comment by digint** [comment]
released v0.3.3, thanks for nagging ;-)

Not bumping to v1.0.0, mainly because it would be a *break* in the versioning scheme. People might think they would have to update, even if they definitively don't (as v0.3.3 adds nothing but some cleanups in examples, makefiles and documentation)

In the long term this probably means: there might never be a v1.0.0, even if TinyFSM is very stable since years now. I will reconsider this on next minor release.
